version: '3.8'
services:
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    networks:
      - hotel-network
    prots:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    hotel-app:
      image: hotel:axiom
      container_name: hotel-axiom
      networks:
        - hotel-network
      ports:
        - "8080:8080"
      environment:
        - APP_SERVER_PORT=8080
        - DB_HOST=postgres-db
        - DB_PORT=5432
        - DB_NAME=hotel_db
        - DB_SCHEMA=hotel_schema
        - DB_USER=postgres
        - DB_PASSWORD=postgres
      depends_on:
        postgres-db:
          condition: service_healthy

networks:
  hotel-network:
    driver: bridge