version: '3.8'
services:
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    networks:
      - hotel-network
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-db:
    image: mongo:7.0
    container_name: mongo-db
    networks:
      - hotel-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: statistics-db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - hotel-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    networks:
      - hotel-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO, kafka.producer.async.DefaultEventHandler=INFO, state.change.logger=INFO"
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$DOCKERHOST:9092, INSIDE://kafka:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  hotel:
    image: hotel:axiom
    container_name: hotel-axiom
    networks:
      - hotel-network
    ports:
      - "8080:8080"
    environment:
      - APP_SERVER_PORT=8080
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=hotel_db
      - DB_SCHEMA=hotel_schema
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MONGODB_HOST=mongo-db
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=statistics-db
      - MONGODB_USER=root
      - MONGODB_PASSWORD=root
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
#    command: ["./app", "-Xmx64m", "-Xms64m"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness"]
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 5s
    depends_on:
      postgres-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hotel-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - hotel-network
    depends_on:
      - prometheus

networks:
  hotel-network:
    driver: bridge